In [3]:
# numpy libraries (numpy stands for numerical python)
import numpy as np
import sys

In [3]:
print(np.__version__)  # to know the version of numpy (numerical Python)
print(sys.version)  # to know the version of Python being used. In this case, it is 3.7.6

1.21.5
3.7.6 (default, Apr  3 2020, 00:02:16) 
[GCC 7.5.0]


In [5]:
# Create a 1-D Array
arr1=np.array([4,5,6,7])
print(arr1)

[4 5 6 7]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
# Arrays are homogeneous
arr1=np.array([4,5,6,7,7.8])
arr1  # data has now converted into float because it wants to keep data in a homogeneous way

array([4. , 5. , 6. , 7. , 7.8])

In [7]:
# Create a 2-D Array
arr2=np.array([[5,6,7,8], [3,4,2,1]], dtype='float')
arr2

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [8]:
print(arr2)

[[5. 6. 7. 8.]
 [3. 4. 2. 1.]]


In [17]:
arr3 = np.arange(16).reshape(1,4,4)
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
arr3.ndim

3

In [21]:
arr3.dtype

dtype('int64')

In [27]:
np.mean(arr3)

7.5

# Attributes of array
1. Shape of the array
2. Number of dimension of the array
3. Data type of the array
4. Item size of the array
5. Number of bytes in the array

In [13]:
arr2.shape  # this shows that it is two 1-D dimension array with 4 elements in each. 

(2, 4)

In [14]:
arr2.ndim

2

In [15]:
arr2.dtype

dtype('float64')

In [18]:
arr2.itemsize  # itemsize returns the space occupied by every element

8

In [19]:
arr2.nbytes

64

In [33]:
# Operation on Array
distance=np.array([10,12,15,17,20])
time = np.array([[0.3,0.4,0.5,0.3,0.9], [0.1,0.2,0.3, 0.4, 0.5]])

In [34]:
distance+time  # Arrays must be same size and shape in order to perform the operation. 

array([[10.3, 12.4, 15.5, 17.3, 20.9],
       [10.1, 12.2, 15.3, 17.4, 20.5]])

In [35]:
distance-time

array([[ 9.7, 11.6, 14.5, 16.7, 19.1],
       [ 9.9, 11.8, 14.7, 16.6, 19.5]])

In [36]:
distance*time

array([[ 3. ,  4.8,  7.5,  5.1, 18. ],
       [ 1. ,  2.4,  4.5,  6.8, 10. ]])

In [37]:
# Access the array elements
distance=np.array([10,12,15,17,20])

In [38]:
distance[0]

10

In [39]:
arr2 

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [40]:
arr2[0]  # This will print the entire first array. 

array([5., 6., 7., 8.])

In [41]:
arr2[0,1] # This will print the second element of the first array

6.0

In [42]:
arr2[0,0]  # This will print the first elements of the first array

5.0

In [43]:
arr2[1,1]

4.0

In [44]:
arr2[1]

array([3., 4., 2., 1.])

In [45]:
# Access first row  with all columns 
arr2[0, :]    # Colon ':' means All - wherever you use it in Python 

array([5., 6., 7., 8.])

In [57]:
#First colum 

arr2

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [58]:
arr2[0, [2,3]]

array([7., 8.])

In [59]:
arr2[:, 1]  # This is to print second column

array([6., 4.])

In [60]:
arr2[:, 0]  # This is to print first column

array([5., 3.])

In [75]:
arr2[:, 2:]  # This prints the last two columns

array([[7., 8.],
       [2., 1.]])

In [76]:
arr3=np.array([[5,6,7,8], [3,4,2,1], [4,7,33,2]])
arr3

array([[ 5,  6,  7,  8],
       [ 3,  4,  2,  1],
       [ 4,  7, 33,  2]])

In [77]:
arr2>3  # This will give you only true or false results, not the value itself.

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [78]:
arr2[arr2>3]  # By doing this you are now getting the value that are greater than 3

array([5., 6., 7., 8., 4.])

In [79]:
arr2[arr2>3].size

5

# Universal Functions that you can apply on your array
1. Mean
2. Median
3. Mode
4. Standard Deviation
5. Variance
6. Square Root
7. Min
8. Max
9. Argmax
10. argmin
11. count

In [93]:
arr1=np.array([2,4,5,6,7])
print(np.mean(arr1))

4.8


In [94]:
print(np.median(arr1))

5.0


In [105]:
arr1=np.array([2,4,5,10, 6,7, 100])  # n/2+(n/2+1)/2
print(np.median(arr1))
# 3rd item+4 rth items/2 5+6/2

6.0


In [106]:
arr1

array([  2,   4,   5,  10,   6,   7, 100])

In [107]:
arr1.sort()

In [108]:
arr1

array([  2,   4,   5,   6,   7,  10, 100])

In [109]:
print(np.median(arr1))

6.0


In [110]:
# mean is good for gettin average but median provides the value that is not impacted by outliers.  
# dataset - missing values - age - fill missing values by mean. 
# salary - CEO salary will be high which will corrupt the mean value but you can find the median value to find the right average. 

In [112]:
print(arr1)
print(np.sqrt(arr1)) # Calculate the square root of all data elements in the array

[  2   4   5   6   7  10 100]
[ 1.41421356  2.          2.23606798  2.44948974  2.64575131  3.16227766
 10.        ]


In [113]:
print(np.min(arr1))

2


In [114]:
print(np.max(arr1))

100


In [116]:
print(np.average(arr1))

19.142857142857142


In [117]:
print(np.argmax(arr1))  # Returns the index of the value which is maximum, In this case, the position of the maximum value is 6th position

6


In [119]:
print(np.argmin(arr1))  # Returns the index of the value which is minimum. In this case, the position of the minimum value is 6th position

0


In [122]:
name=np.array(['hari', 'hari', 'hari', 'hari', 'hari', 'John', 'Ruby'])

In [123]:
name[6]

'Ruby'

In [5]:
# mathematicalfunctions
# reshape the numpy array 
# next time we will be working with panda 
# In the meantime we will be learning statistics
# go through the video

In [6]:
arr1=np.array([2,4,5,6,7, 10, 100])

In [7]:
print(np.var(arr1))

1094.9795918367347


In [8]:
print(np.std(arr1))

33.09047584784381


In [12]:
print(np.sqrt(arr1))

[ 1.41421356  2.          2.23606798  2.44948974  2.64575131  3.16227766
 10.        ]


# Reshape the array

In [35]:
# 2-D Array to 1-D Array

arr1=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [36]:
arr1.shape

(3, 3)

In [37]:
arr1.ndim

2

In [38]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr1.ndim

2

In [77]:
# Convert 2-D Array into 1-D Array
oned=arr1.flatten()  # Flatten is used to convert any 2,3,4 or more dimensional arrays into 1-D array

In [78]:
oned

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# Convert 2-D Array into 3-D Array
# reshape
new=arr1.reshape(3,3,1)  # Reshape must be sensible otherwise it will throw error. 
                         # Here 3x3x1 = 9 and because the array has 9 elements, it can convert 
new

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [80]:
new.ndim

3

In [81]:
new1=arr1.reshape(9,1)

In [82]:
new1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [92]:
new1[:8:2]

array([[1],
       [3],
       [5],
       [7]])

# How to create 1-D Array 

In [26]:
# arange () function will help create the array quickly 
new=np.arange(10)

In [27]:
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
new1=np.arange(15).reshape(3,1,5)

In [96]:
new1

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [100]:
new1[0:2]

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [31]:
new=np.arange(5,21)

In [32]:
new.size

16

In [35]:
#Create 1-D Array of 12 Elements and Reshape into 2-D Array
new=np.arange(12).reshape(3,4)

In [36]:
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
new=np.arange(12).reshape(4,3)

In [38]:
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
new.ndim

2

## Create different types of matrices 

In [42]:
# Zero matrix
arr_zero=np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

In [43]:
arr_zero=np.zeros([2,3], dtype='int')

In [44]:
arr_zero

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
arr_ones=np.ones([2,3], dtype='int')
arr_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
arr1=np.eye(5, dtype='int')
arr1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [49]:
# Random Numbers
arr1=np.random.rand(5)

In [50]:
arr1

array([0.39023901, 0.04177751, 0.47588911, 0.08186923, 0.21498802])

In [55]:
np.random.rand(3,2)

array([[0.5679078 , 0.44372734],
       [0.83311556, 0.73014513],
       [0.51210463, 0.86454886]])

In [63]:
np.random.randint(10)

6

In [66]:
np.random.randint(10, 30)

22

In [68]:
np.random.randint(10, 30, (3)) # This is to get random integer numbers between 10 and 30 in set of 3 random numbers

array([19, 21, 25])

In [69]:
np.random.randint(10, 30, (2,2)) # This is to get 2-D Array values in return

array([[27, 29],
       [12, 18]])

In [40]:
np.random.random((5,5))
# In Machine Learning, you will learn about Random Forest. 

array([[0.98860699, 0.98724806, 0.47340576, 0.45205855, 0.26917744],
       [0.97543746, 0.15660302, 0.31142728, 0.69177854, 0.93756299],
       [0.39491764, 0.59909485, 0.40579863, 0.53019877, 0.75493084],
       [0.9891459 , 0.12204843, 0.1085206 , 0.13844628, 0.80053416],
       [0.36128371, 0.1177094 , 0.59390455, 0.46374107, 0.95132752]])

In [55]:
arr5=np.random.randint(10,30, size=(2,3,3))
arr5

array([[[16, 29, 29],
        [13, 12, 27],
        [25, 12, 19]],

       [[25, 24, 16],
        [25, 22, 12],
        [25, 25, 16]]])

In [75]:
arr5[0::-1]

array([[[16, 29, 29],
        [13, 12, 27],
        [25, 12, 19]]])

# Linspace Function

In [107]:
# Linspace Function
# Create 100 numbers in some range with equal interval
np.linspace(0,100, num=100, dtype=int)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98, 100])

In [79]:
np.linspace(1,30, num=50)

array([ 1.        ,  1.59183673,  2.18367347,  2.7755102 ,  3.36734694,
        3.95918367,  4.55102041,  5.14285714,  5.73469388,  6.32653061,
        6.91836735,  7.51020408,  8.10204082,  8.69387755,  9.28571429,
        9.87755102, 10.46938776, 11.06122449, 11.65306122, 12.24489796,
       12.83673469, 13.42857143, 14.02040816, 14.6122449 , 15.20408163,
       15.79591837, 16.3877551 , 16.97959184, 17.57142857, 18.16326531,
       18.75510204, 19.34693878, 19.93877551, 20.53061224, 21.12244898,
       21.71428571, 22.30612245, 22.89795918, 23.48979592, 24.08163265,
       24.67346939, 25.26530612, 25.85714286, 26.44897959, 27.04081633,
       27.63265306, 28.2244898 , 28.81632653, 29.40816327, 30.        ])

In [80]:
np.linspace(1,30, num=50, dtype='int')

array([ 1,  1,  2,  2,  3,  3,  4,  5,  5,  6,  6,  7,  8,  8,  9,  9, 10,
       11, 11, 12, 12, 13, 14, 14, 15, 15, 16, 16, 17, 18, 18, 19, 19, 20,
       21, 21, 22, 22, 23, 24, 24, 25, 25, 26, 27, 27, 28, 28, 29, 30])

In [81]:
np.linspace(1, 100, num=50, dtype='int')

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [102]:
c=np.array([[1,2], [3,4]], dtype=complex) # This creates a complex array
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [104]:
np.empty((2,3)) 

array([[4.68403704e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [110]:
e=np.arange(1,5)
e

array([1, 2, 3, 4])

In [111]:
np.exp(e)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [114]:
a=np.arange(5)**3
a

array([ 0,  1,  8, 27, 64])

In [121]:
def f(x,y):
    return 3*x+y

b=np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15]])

In [124]:
def f2(x,y):
    return 1*x+y

c=np.fromfunction(f2, (5,4), dtype=int)
c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [125]:
d= b+c
d

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [126]:
e = b-c
e

array([[0, 0, 0, 0],
       [2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6],
       [8, 8, 8, 8]])

In [128]:
m=b*c
m

array([[  0,   1,   4,   9],
       [  3,   8,  15,  24],
       [ 12,  21,  32,  45],
       [ 27,  40,  55,  72],
       [ 48,  65,  84, 105]])

In [134]:
di=b/c
di

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       nan, 1.        , 1.        , 1.        ],
       [3.        , 2.        , 1.66666667, 1.5       ],
       [3.        , 2.33333333, 2.        , 1.8       ],
       [3.        , 2.5       , 2.2       , 2.        ],
       [3.        , 2.6       , 2.33333333, 2.14285714]])

In [139]:
c.nonzero()

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))