In [2]:
# numpy libraries (numpy stands for numerical python)

import numpy as np
import sys

In [3]:
print(np.__version__)  # to know the version of numpy (numerical Python)
print(sys.version)  # to know the version of Python being used. In this case, it is 3.7.6

1.21.5
3.7.6 (default, Apr  3 2020, 00:02:16) 
[GCC 7.5.0]


In [6]:
# Create a 1-D Array
arr1=np.array([4,5,6,7])
print(arr1)

[4 5 6 7]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
# Arrays are homogeneous
arr1=np.array([4,5,6,7,7.8])
arr1  # data has now converted into float because it wants to keep data in a homogeneous way

array([4. , 5. , 6. , 7. , 7.8])

In [10]:
# Create a 2-D Array
arr2=np.array([[5,6,7,8], [3,4,2,1]], dtype='float')
arr2

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [11]:
print(arr2)

[[5. 6. 7. 8.]
 [3. 4. 2. 1.]]


# Attributes of array
1. Shape of the array
2. Number of dimension of the array
3. Data type of the array
4. Item size of the array
5. Number of bytes in the array

In [13]:
arr2.shape  # this shows that it is two 1-D dimension array with 4 elements in each. 

(2, 4)

In [14]:
arr2.ndim

2

In [15]:
arr2.dtype

dtype('float64')

In [18]:
arr2.itemsize  # itemsize returns the space occupied by every element

8

In [19]:
arr2.nbytes

64

In [33]:
# Operation on Array
distance=np.array([10,12,15,17,20])
time = np.array([[0.3,0.4,0.5,0.3,0.9], [0.1,0.2,0.3, 0.4, 0.5]])

In [34]:
distance+time  # Arrays must be same size and shape in order to perform the operation. 

array([[10.3, 12.4, 15.5, 17.3, 20.9],
       [10.1, 12.2, 15.3, 17.4, 20.5]])

In [35]:
distance-time

array([[ 9.7, 11.6, 14.5, 16.7, 19.1],
       [ 9.9, 11.8, 14.7, 16.6, 19.5]])

In [36]:
distance*time

array([[ 3. ,  4.8,  7.5,  5.1, 18. ],
       [ 1. ,  2.4,  4.5,  6.8, 10. ]])

In [37]:
# Access the array elements
distance=np.array([10,12,15,17,20])

In [38]:
distance[0]

10

In [39]:
arr2 

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [40]:
arr2[0]  # This will print the entire first array. 

array([5., 6., 7., 8.])

In [41]:
arr2[0,1] # This will print the second element of the first array

6.0

In [42]:
arr2[0,0]  # This will print the first elements of the first array

5.0

In [43]:
arr2[1,1]

4.0

In [44]:
arr2[1]

array([3., 4., 2., 1.])

In [45]:
# Access first row  with all columns 
arr2[0, :]    # Colon ':' means All - wherever you use it in Python 

array([5., 6., 7., 8.])

In [57]:
#First colum 

arr2

array([[5., 6., 7., 8.],
       [3., 4., 2., 1.]])

In [58]:
arr2[0, [2,3]]

array([7., 8.])

In [59]:
arr2[:, 1]  # This is to print second column

array([6., 4.])

In [60]:
arr2[:, 0]  # This is to print first column

array([5., 3.])

In [75]:
arr2[:, 2:]  # This prints the last two columns

array([[7., 8.],
       [2., 1.]])

In [76]:
arr3=np.array([[5,6,7,8], [3,4,2,1], [4,7,33,2]])
arr3

array([[ 5,  6,  7,  8],
       [ 3,  4,  2,  1],
       [ 4,  7, 33,  2]])

In [77]:
arr2>3  # This will give you only true or false results, not the value itself.

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [78]:
arr2[arr2>3]  # By doing this you are now getting the value that are greater than 3

array([5., 6., 7., 8., 4.])

In [79]:
arr2[arr2>3].size

5

# Universal Functions that you can apply on your array
1. Mean
2. Median
3. Mode
4. Standard Deviation
5. Variance
6. Square Root
7. Min
8. Max
9. Argmax
10. argmin
11. count

In [93]:
arr1=np.array([2,4,5,6,7])
print(np.mean(arr1))

4.8


In [94]:
print(np.median(arr1))

5.0


In [105]:
arr1=np.array([2,4,5,10, 6,7, 100])  # n/2+(n/2+1)/2
print(np.median(arr1))
# 3rd item+4 rth items/2 5+6/2

6.0


In [106]:
arr1

array([  2,   4,   5,  10,   6,   7, 100])

In [107]:
arr1.sort()

In [108]:
arr1

array([  2,   4,   5,   6,   7,  10, 100])

In [109]:
print(np.median(arr1))

6.0


In [110]:
# mean is good for gettin average but median provides the value that is not impacted by outliers.  
# dataset - missing values - age - fill missing values by mean. 
# salary - CEO salary will be high which will corrupt the mean value but you can find the median value to find the right average. 

In [112]:
print(arr1)
print(np.sqrt(arr1)) # Calculate the square root of all data elements in the array

[  2   4   5   6   7  10 100]
[ 1.41421356  2.          2.23606798  2.44948974  2.64575131  3.16227766
 10.        ]


In [113]:
print(np.min(arr1))

2


In [114]:
print(np.max(arr1))

100


In [116]:
print(np.average(arr1))

19.142857142857142


In [117]:
print(np.argmax(arr1))  # Returns the index of the value which is maximum, In this case, the position of the maximum value is 6th position

6


In [119]:
print(np.argmin(arr1))  # Returns the index of the value which is minimum. In this case, the position of the minimum value is 6th position

0


In [122]:
name=np.array(['hari', 'hari', 'hari', 'hari', 'hari', 'John', 'Ruby'])

In [123]:
name[6]

'Ruby'

In [ ]:
# mathematicalfunctions
# reshape the numpy array 
# next time we will be working with panda 
# In the meantime we will be learning statistics
# go through the video